### ISSUE TITLE
Lap times don't always calculate correctly

### ISSUE THREAD

**Issue by randyzwitch** [alessandrobessi/pytelemetry#18]
During time trial, if I cancel out of the session then CTRL-C to cancel the listener, I get the following:

```python
^CTraceback (most recent call last):
  File "cli.py", line 34, in listen
    telemetry.save_data()
  File "/home/randyzwitch/github_work/pytelemetry/pytelemetry/listen.py", line 85, in save_data
    for packet_type, packet_data in self.listen():
  File "/home/randyzwitch/github_work/pytelemetry/pytelemetry/listen.py", line 54, in listen
    data, _ = self.socket.recvfrom(self.buffer_size)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 58, in <module>
    CLI()
  File "cli.py", line 28, in __init__
    getattr(self, command)()
  File "cli.py", line 36, in listen
    telemetry.save_before_exit()
  File "/home/randyzwitch/github_work/pytelemetry/pytelemetry/listen.py", line 107, in save_before_exit
    f.write("Lap {}: {}\n".format(k, get_lap_time(v)))
  File "/home/randyzwitch/github_work/pytelemetry/pytelemetry/helpers.py", line 7, in get_lap_time
    time, speed, throttle, steer, brake, clutch, gear, engine, drs = zip(*data)
ValueError: not enough values to unpack (expected 9, got 0)
```

Not sure how I'm supposed to shut down the listener, but I have seen the lap times work before

**Comment by webbrain-one** [comment]
Thanks for the detailed traceback! I've opened a pull request to fix this: #20. 

It adds a check to handle empty lap data gracefully during the shutdown process, which prevents the `ValueError` crash when canceling out of a time trial session. 

Let me know if you'd like to take a look or have any feedback! 🏎️💨
